#' Add backticks around a string
#' 
#' Mostly for column names with special characters, add a backtick
#' before and after string 
#' 
#' @param str   character string
#'
#' @return str with backticks added to beginning and end
add_ticks <- function(str){
    paste0("`",str,"`")
}

#' Remove leading or trailing backticks from string
#'
#' Remove leading or trailing backticks from string
#'
#' @param str   character string containing backticks
#'
#' @return str with backticks removed
remove_ticks <- function(str){
    gsub("^`","",gsub("`$","",str))
}

#' Get standard star notation of a numeric value
#' 
#' Get standard star notation of a numeric value, generally a p.value; 
#' val < 0.001 = "***", val < 0.01 = "**", val < 0.05 = "*"
#'
#' @param val   numeric value
#' @return character string of stars, the length of which signifies significance
signifStars <- function(val){
    ifelse(val < 0.001, "***",
           ifelse(val < 0.01, "**",
                  ifelse(val < 0.05, "*", "")))
}

#' Insert newlines into a long character string
#'
#' Wrap a long character string by inserting newline characters wherever appropriate
#' 
#' @param longStr    character string to be wrapped
#' @param maxChar    integer; the maximum number of characters allowed on one line
#'
#' @return wrapped character sring
wrapTitle <- function(longStr, maxChar=60){
    if(nchar(longStr) <= maxChar || grepl("\n",longStr)){ return(longStr) }

    finalStr <- ""
    for(x in 1:(ceiling(nchar(longStr)/maxChar))){
        part <- substr(longStr, maxChar*(x-1)+1, maxChar*x)
        if(!nchar(part) < maxChar){
            spcs  <- grep(" |/",unlist(strsplit(part, "")))
            lnBrk <- spcs[which(abs(spcs - maxChar) == min(abs(spcs - maxChar)))]
            part  <- paste0(replace(unlist(strsplit(part,"")), lnBrk, c("\n")),collapse="")
        }
        finalStr <- paste0(finalStr, part)
    }
    finalStr
}

#' Extract a legend from a gplot
#' 
#' Extract a legend from a plot generated with ggplot
#' 
#' @param plt    a plot generated with ggplot 
getLegend <- function(plt){
    tmp <- tryCatch({
               ggplot_gtable(ggplot_build(plt))
             }, error=function(e){
               plt
             })
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    return(legend)
}

#' Get legend from a gplot
#' 
#' Given a plot generated with ggplot(), separate and return only
#' the legend component
#' 
#' @param a.gplot  a plot generated by ggplot()
#' @return  the legend of a.gplot 
g_legend <- getLegend


#' Remove a legend from a gplot
#' 
#' Remove a legend from a gplot
#'
#' @param plt    a plot generated with ggplot 
removeLegend <- function(plt){
    tmp <- ggplot_gtable(ggplot_build(plt))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    tmp$grobs[[leg]] <- NULL
    return(tmp)
}

#' Force two ggplot table objects to have the same height
#'
#' Given two ggplot table objects, change the height of the second
#' to match the first
#'
#' @param g1  a ggplot table object from which to pull the desired height
#' @param g2  a ggplot table object; the height of this object will be
#'            changed to the height value of g1
#' 
#' @return a list where each element is one of the ggplot tables passed
#'         to the function, with the height of the second changed to equal
#'         the height of the first
matchPanelHeights <- function(g1, g2){

    panelIDs <- unique(g1$layout[grepl("panel", g1$layout$name), "t"])
    heights <- g1$heights[panelIDs]

    g2$heights[panelIDs] <- unit.c(do.call(unit, list(heights, 'null')))

    return(list(g1,g2))
}

getPlotColors <- function(plotColors = NULL, plotConfig = NULL){
    if(is.null(plotColors)){
        return(read_yaml(cfg$plot_config_file)$plot_colors)
    }
    plotColors
}

